### ISSUE TITLE
重要bug，请留下你的支付宝账户，我要测试能不能使用

### ISSUE THREAD

**Issue by wsd1** [thundernet8/AlipayOrdersSupervisor#1]
Hi，吴学谦，从你开源的东西收益良多，请留下支付宝。
我的微信号是 ws_dingyi，请加我也可以。

**Comment by thundernet8** [comment]
这是测试链接，和WordPress主题集成的，https://webapproach.net/shop/experience-tint-qr-pay.html

**Comment by thundernet8** [comment]
ok

**Comment by thundernet8** [comment]
@wsd1 
请参考 [有赞云和有赞微小店实现个人收款解决方案](https://github.com/thundernet8/YouzanPayPortal) 新思路
