### ISSUE TITLE
地址该换了

### ISSUE THREAD

**Issue by yuandalu** [thundernet8/AlipayOrdersSupervisor#10]
已经换成
https://consumeprod.alipay.com/record/advanced.htm?_input_charset=utf-8
了
之前的提示风险

**Comment by thundernet8** [comment]
没区别呀，我直接过滤记录只显示收入 `fundFlow=in`

**Comment by yuandalu** [comment]
之前稳定用了半个月 按理说经常在那台ip登录（linux），最近不知道为啥 老提示扫码查看，要么就是cookie过期，从不上网页版，偶尔上下app，你遇到没
