### ISSUE TITLE
如何区分新订单？

### ISSUE THREAD

**Issue by jaweii** [thundernet8/AlipayOrdersSupervisor#11]
我使用了下，发现似乎 这个插件就是每分钟把爬到的第一页订单数据发送到通知服务器。

如果是这样，服务器已经处理过的订单，还会再次收到通知，没有必要呀。

我觉得可以这样，就是通知服务器后，要求服务器返回一个指定状态码，插件收到这个状态码，就视作服务器已经处理这个通知了，下次通知就不发这个订单数据，只发新订单数据，如果没有新订单，就不请求服务器。
（我使用过的第三方支付集成平台，诸如PING XX、BeeCloud，都是这样的）

**Comment by thundernet8** [comment]
[Ignore](https://github.com/thundernet8/AlipayOrdersSupervisor/blob/aae7672830cd4066ba520900d1744e75338ee75e/src/alipay.ts#L236)

**Comment by jaweii** [comment]
写在文档里嘛

**Comment by thundernet8** [comment]
@jaweii 加了
