### ISSUE TITLE
我试了几个支付宝，只有一个可用

### ISSUE THREAD

**Issue by raykwok** [thundernet8/AlipayOrdersSupervisor#2]
其中可用的是我常用的支付宝，不知道为何，如何去解决？我可以提供cookie给你测试。

**Comment by thundernet8** [comment]
@raykwok 我也不确定你的其他账号有什么特别属性，但是你给cookies给我这是不合适的

**Comment by raykwok** [comment]
已找到问题，应该是支付宝安全控制方面的，我通过服务器作为代理在web登录一次后就没问题了。
