### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by Tigeraus** [thundernet8/AlipayOrdersSupervisor#3]
```
{ Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'ECONNECTION', command: 'CONN' }
```

**Comment by thundernet8** [comment]
你的运行环境应该设置了代理，尝试
```
unset http_proxy
unset https_proxy
```

**Comment by Tigeraus** [comment]
实测无效，更换网络环境也没有效果

**Comment by qjhe** [comment]
cookie 基本是5-10分钟就失效了 有解吗？

**Comment by thundernet8** [comment]
@qjhe 我上一次cookie从2月底坚持到6月底，新开的现在都在正常运行半个月了

注意设置了cookies了之后，就不要去登录网页版，更不能停留在网页导致过长时间无操作，会话直接失效

**Comment by qjhe** [comment]
我测试了几次都不行呢。。其他的获取数据都 没问题 就是10分钟左右cookie失效。。
登录支付宝网页  打印完cookie 放到项目，就关闭网页了。。也没再登录还是失效了
纠结啊

**Comment by qjhe** [comment]
您试过企业支付宝账号吗 那个也是cookie一直可用吗

**Comment by thundernet8** [comment]
没有 这个可能安全防范更高吧 有企业支付宝 那可以申请支付宝即时到帐了啊 没必要用这个

**Comment by DreamCatcherJ** [comment]
document.cookie 是全部复制进去么，会收到Maybe the cookies has expired, please update it and restart the supervisor邮件

**Comment by thundernet8** [comment]
@DreamCatcherJ 注意一下 登录后会跳转标准版订单列表 你切换到高级版订单列表然后获取cookie

**Comment by ifengchao** [comment]
获取到cookie，要把登陆的页面关闭还是要怎么样？

**Comment by thundernet8** [comment]
尽快关闭 不要在页面停留过久无操作导致会话过期

发自我的 iPhone
