### ISSUE TITLE
不能获取document.cookie

### ISSUE THREAD

**Issue by tjt852** [thundernet8/AlipayOrdersSupervisor#5]
我用chrome和火狐都试过了都搜索不到document.cookie的值，这是我获取的请求头部信息，我分别使用过响应头里的Set-Cookie和请求头里的Cookie试过，都提示我Cookie超时，，请问我获取的方式对吗？
![f5a536df-c0f1-4246-b175-1339622b8d29](https://user-images.githubusercontent.com/5794936/31223489-10257966-a9fd-11e7-83f4-61466d45288c.png)

**Comment by tjt852** [comment]
还请码主帮看看哦

**Comment by thundernet8** [comment]
你在console里面输入document.cookie没输出？

发自我的 iPhone

**Comment by tjt852** [comment]
@thundernet8 在chrome和火狐里面都试过了，确定没有输出
![591930dc-653b-48ea-a8ff-58c244831736](https://user-images.githubusercontent.com/5794936/31323395-d5c671e6-acd9-11e7-84f2-63648ac2c173.png)

**Comment by thundernet8** [comment]
不是在那个输入框 是下面那个>那里输入回车

发自我的 iPhone

**Comment by tjt852** [comment]
@thundernet8 不好意思，是我的问题，现在获取到了，我配置了接受通知的服务器api地址，我测试转账后发现没有被调用，帮我看看配置的对不对，我没配pushAppId、pushAppKey、pushStateSecret这三个关系不大吧？
![99bea418-a285-4f84-9471-580176007bf4](https://user-images.githubusercontent.com/5794936/31331155-e378a9fe-aca6-11e7-95c7-4bf57cfb46f3.png)，对了我配置cookie后过个差不多四五分钟后就发邮件提示我超时，之前没配置正确马上就会发，我获取到cookie后直接把浏览器也退出了，就是说四五分钟后cookie就会超时，是不是现在支付宝的cookie时效变啦？

**Comment by tjt852** [comment]
@thundernet8 码主，还在吗？

**Comment by tjt852** [comment]
@thundernet8 订单失效的问题已经好了，，，我切换到高级版本就几个小时过去了也没有失效，，还请码主在README里面说清楚一点以免后人少走弯路，至于推送信息接收不到问题也解决了
