### ISSUE TITLE
lz请教一个问题，这个项目是处理后半部分的订单状态同步，前半部分的支付怎么实现？

### ISSUE THREAD

**Issue by qxwei** [thundernet8/AlipayOrdersSupervisor#6]
lz请教一个问题，这个项目是处理后半部分的订单状态同步，前半部分的支付怎么实现？

**Comment by thundernet8** [comment]
这个只抓取支付宝交易记录，记录上附带的备注用于关联自己系统的订单，服务器接收到本脚本的通知会包含订单信息以及订单备注，在自己订单系统根据备注找订单，然后更新订单状态

https://webapproach.net/shop/experience-tint-qr-pay.html

**Comment by tjt852** [comment]
@qxwei 想问一下这位朋友你的cookie会段时间失效吗？我测试转账，，，回调并没有调用

**Comment by tjt852** [comment]
@qxwei 我的问题解决了
