### ISSUE TITLE
经常每隔半天跳出需要扫描二维码

### ISSUE THREAD

**Issue by wuchujiecode** [thundernet8/AlipayOrdersSupervisor#8]
请问这种情况怎么破。经常爬着爬着半天左右要跳一次二维码扫描的页面

**Comment by thundernet8** [comment]
触发了支付宝安全校验吧，只能扫一下了，有可能下一次会好一段时间，也可能还是会这样，没有办法的

**Comment by thundernet8** [comment]
@wuchujiecode
请参考 [有赞云和有赞微小店实现个人收款解决方案](https://github.com/thundernet8/YouzanPayPortal) 新思路
